name: Check README for Broken Links

on:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check README links
        id: check-links
        run: |
          markdown-link-check README.md > link-check-results.txt || true

      - name: Display Results
        run: |
          echo "#### Link Check Results ####"
          cat link-check-results.txt

      - name: Fail if Broken Links Found
        if: always()
        run: |
          if grep -q "ERROR" link-check-results.txt; then
            echo "Broken links were found:"
            cat link-check-results.txt
            exit 1
          else
            echo "No broken links found! All links are valid."
          fi
