name: Check README for Broken Links

on:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check README links
        id: check-links
        run: |
          markdown-link-check --verbose README.md > link-check-results.txt || true
          echo "::group::Link Check Results"
          cat link-check-results.txt
          echo "::endgroup::"

      - name: Annotate Results
        run: |
          if grep -q "ERROR:" link-check-results.txt; then
            echo "::error title=Broken Links Found::$(cat link-check-results.txt | grep -B 2 'ERROR' | sed 's/%/%25/g; s/\n/%0A/g; s/\r/%0D/g')"
            echo "Broken Links:"
            cat link-check-results.txt | grep -B 2 'ERROR'
            exit 1
          else
            echo "::notice title=No Broken Links Found::All links are valid in the README."
          fi
