name: Check README for Broken Links

on:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check README links
        id: check-links
        run: |
          markdown-link-check --verbose README.md > link-check-results.txt || true
          echo "::group::Link Check Results"
          cat link-check-results.txt
          echo "::endgroup::"

      - name: Annotate Results
        run: |
          if grep -q "✖" link-check-results.txt; then
            echo "::error title=Broken Links Found::The following links are broken:"
            grep -B 1 "✖" link-check-results.txt | sed 's/%/%25/g; s/\n/%0A/g; s/\r/%0D/g'
            echo "Full Details:"
            cat link-check-results.txt | grep -B 1 "✖"
            exit 1
          else
            echo "::notice title=All Links Valid::All links in the README are valid."
          fi
