name: Check README for Broken Links

on:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-22.04  # Updated to explicitly specify Ubuntu 22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Check README links
        id: check-links
        run: |
          markdown-link-check README.md > link-check-results.txt || true  # Avoid failing the workflow

      - name: Process Results
        id: process-results
        run: |
          if grep -q "ERROR" link-check-results.txt; then
            echo "broken_links=true" >> $GITHUB_ENV
            echo "$(cat link-check-results.txt)" > broken-links-report.txt
          else
            echo "broken_links=false" >> $GITHUB_ENV
            echo "All links are valid!" > broken-links-report.txt
          fi

      - name: Notify GarlicRot
        if: always()  # Ensure this runs even if previous steps fail
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('broken-links-report.txt', 'utf8');
            const brokenLinks = process.env.broken_links === 'true';
            const body = brokenLinks
              ? `### ⚠️ Broken Links Found\nHi @GarlicRot, the following broken links were detected:\n\`\`\`\n${report}\n\`\`\`\nPlease address them!`
              : `### ✅ All Links Valid\nHi @GarlicRot, all links in the README are valid! Great job!`;
            
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: body,
            });
