name: Generate MD from YAML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Generate markdown files
        run: python scripts/generate.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'PLUGINS.md THEMES.md README.md'
          message: 'Update PLUGINS.md, THEMES.md, and README.md from YAML'
          push: true
