name: Validate and Generate Markdown

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Validate YAML file
        run: python scripts/validate-yml.py

      - name: Generate Markdown files
        if: success() # Only run if validation passes
        run: python scripts/generate.py

      - name: Commit and push changes
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'PLUGINS.md THEMES.md README.md'
          message: 'Update PLUGINS.md, THEMES.md, and README.md from YAML'
          push: true
